baseURL                   = "https://zxdawn.github.io"
builddrafts                = false
languageCode               = "zn-Hans"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = ["AllinOne", "resume"]
title                      = "Dreambooker"

pygmentsuseclasses         = true

[outputFormats.resume]
  baseName = "index"
  mediaType = "text/html"
  isHTML = true

[permalinks]
  sci-tech                 = ":year/:month/:day/:slug/"
  essay                     = ":year/:month/:day/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Sci-Tech"
    weight                 = 1
    identifier             = "sci-tech"
    url                    = "sci-tech/"

  [[menu.main]]
    name                   = "Essay"
    weight                 = 3
    identifier             = "essay"
    url                    = "essay/"

  [[menu.main]]
    name                   = "About"
    weight                 = 9
    identifier             = "about"
    url                    = "about/"

 

[params]
  faviconfile              = "img/logo.jpg"
  avatar                   = "img/me.jpg"
  author                   = "Xin Zhang"
  description              = ["Life is a dream,", "Dream is a life."]
  welcome_head             = "Hello, Dreambooker!"
  welcome_word             = "~ Chase your dream ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false

  # slides
  slidesDirPath            = "static/img/header-slides"    # path to image in local dir (for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true


  # links
  email                    = "xinzhang1215@gmail.com"
  github                   = "//github.com/zxdawn"
  twitter                  = "//twitter.com/zhangxin_dawn"
  instagram                = "//instagram.com/zhangxin_dawn/"
  include_rss              = true                         # include RSS <link> tag in <head> and show RSS icon

  # about
  firstName = "Xin"
  lastName = "Zhang"
  address = "Nanjing, CN"
  phone = "+86 15895938361"
  contactNote = "Mr."
  profileImage = "img/portrait.jpg"
  favicon = "images/favicon.ico"

  showSkills = true
  showProjects = false
  showOpenSource = true
  showPublications = true
  showExperience = false
  showEducation = true
  showBlog = true
  showQr = true

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/zxdawn/"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/zhangxin_dawn/"

[[params.handles]]
    name = "Youtube"
    link = "https://www.youtube.com/channel/UC2y2YOGOWZXmOKzR1h_8wGw"

[[params.handles]]
    name = "Instagram"
    link = "https://www.instagram.com/zhangxin_dawn/"

[[params.handles]]
    name = "Facebook"
    link = "https://www.facebook.com/zxdawn"

[params.staticman]
  endpoint = "https://ta1tk27bs2.execute-api.us-east-2.amazonaws.com/prod/v2/entry/github"
  username = "zxdawn"
  repository = "zxdawn.github.io"
  branch = "main"
  githubPullURL = true
  notifications = true